# Generated by Django 4.1.7 on 2023-04-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_lista_listacompras_rename_preoo_aplicacao_preco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListaCompras',
        ),
    ]
