# Generated by Django 4.1.7 on 2023-04-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_compra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
